cadena="hola me llamo Gaby"
cadena2=cadena.replace('a','A')
print(cadena2)
print(cadena[14])
print(cadena.upper())
print(cadena.lower())
print(cadena.capitalize())
print(len(cadena))
print(cadena.swapcase())
print("hola me llamo Gaby".find('llamo'))
print("hola me llamo Gaby".rfind('me'))
